eureka:
   client:
      register-with-eureka: true
      fetch-regisry: true
      service-url:
         defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost
microservice:
  microservice:
   payment-service:
      enpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/payments/doPayment
   order-service:
      enpoints:
         endpoint:
            uri: http://ORDER-SERVICE/orders/bokOrder
